dist: xenial
language: java
jdk:
- openjdk8
#- openjdk11

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: script
  script: mvn deploy -Dmaven.test.skip -s settings.xml
  skip_cleanup: true
  on:
    branch: develop

addons:
  sonarcloud:
    organization: "thuisapp"
    token: $SONAR_TOKEN

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
