language: java
jdk:
- oraclejdk8
- oraclejdk11

deploy:
  provider: script
  script: mvn deploy -Dmaven.test.skip -s settings.xml
  skip_cleanup: true

addons:
  sonarcloud:
    organization: "thuisapp"
    token: $SONAR_TOKEN

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
